use notan::prelude::*;

pub const COLON_NUM: usize = 10;
pub const VAIANTS: [usize; 3] = [0, 1, 2];

pub fn load_num_textures(gfx: &mut Graphics) -> [Texture; 30] {
  let num_textures: [Texture; 30] = [
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-0-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-0-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-0-2.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-1-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-1-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-1-2.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-2-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-2-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-2-2.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-3-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-3-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-3-2.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-4-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-4-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-4-2.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-5-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-5-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-5-2.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-6-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-6-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-6-2.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-7-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-7-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-7-2.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-8-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-8-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-8-2.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-9-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-9-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/num-9-2.png"))
      .build()
      .unwrap(),
  ];

  num_textures
}

pub fn load_colon_textures(gfx: &mut Graphics) -> [Texture; 3] {
  let colon_textures: [Texture; 3] = [
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/colon-0.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/colon-1.png"))
      .build()
      .unwrap(),
    gfx
      .create_texture()
      .from_image(include_bytes!("assets/colon-2.png"))
      .build()
      .unwrap(),
  ];
  colon_textures
}
